import { readdirSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const photosDir = join(__dirname, "..", "public", "assets", "photos");
const outFile = join(__dirname, "..", "src", "data", "photoManifest.ts");

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp", ".gif"]);

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

const files = readdirSync(photosDir)
  .filter((name) => {
    const ext = name.slice(name.lastIndexOf(".")).toLowerCase();
    return IMAGE_EXT.has(ext);
  })
  .map((name) => `/assets/photos/${name}`);

const shuffled = shuffle(files);

const content = `/** Auto-generated by scripts/sync-photos.mjs — do not edit manually */
export const PHOTO_MANIFEST: string[] = ${JSON.stringify(shuffled, null, 2)};

export const PHOTO_COUNT = ${shuffled.length};
`;

writeFileSync(outFile, content);

console.log(`Synced ${shuffled.length} photos (random order) → src/data/photoManifest.ts`);
